[package]
name = "prefetch-rs"
version = "0.1.0"
authors = ["Mathias Iversen <contact@mathiasiversen.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
lto = true
